import type { Artwork } from "./types"

export const artworks: Artwork[] = [
  {
    id: "mask-bwa",
    title: {
      fr: "Masque Dogon",
      en: "Dogon Mask",
      wo: "Maask Dogon",
    },
    description: {
      fr: "Ce masque cérémoniel Dogon du Mali représente un esprit ancestral. Utilisé lors de rituels funéraires, il incarne la connexion entre le monde des vivants et celui des ancêtres. Les Dogons sont réputés pour leur cosmogonie complexe et leurs traditions artistiques millénaires.",
      en: "This ceremonial Dogon mask from Mali represents an ancestral spirit. Used in funeral rituals, it embodies the connection between the world of the living and that of the ancestors. The Dogon are renowned for their complex cosmogony and thousand-year-old artistic traditions.",
      wo: "Maask Dogon bii jëkk na ci Mali, dafa melni ruu jabar. Dañu ko jëfandikoo ci sérémoniy ñu def bu ku dee, te dafa wone lëkkalekaay ci àdduna bu ñu moom ak sa yaay ak sa baay yu dee. Dogon yi dañu bari ci xam-xam bu rafet ak cosaan yu guddi.",
    },
    artist: "Artisan Dogon",
    period: "19ème siècle",
    origin: "Mali",
    category: "Sculpture",
    model3dUrl: "/dogon2.glb",
    imageUrl: "/dogon.jpg",
    qrCode: "MCN-001",
    audioUrl: "/audio/mask-dogon.mp3",
  },
  {
    id: "statue-dogon",
    title: {
      fr: "Statue Nok",
      en: "Nok Statue",
      wo: "Statiy Nok",
    },
    description: {
      fr: "Cette terre cuite de la culture Nok (500 av. J.-C. - 200 ap. J.-C.) du Nigeria est l'une des plus anciennes sculptures d'Afrique subsaharienne. Les Nok maîtrisaient la métallurgie du fer et créaient des œuvres d'une sophistication remarquable.",
      en: "This terracotta from the Nok culture (500 BC - 200 AD) of Nigeria is one of the oldest sculptures in sub-Saharan Africa. The Nok mastered iron metallurgy and created works of remarkable sophistication.",
      wo: "Teer kuit bii jëkk na ci cosaan Nok (500 av. J.-C. - 200 ap. J.-C.) ci Nigeria, te dafa am ci yëf yu mag yu Afrik subsaharienne. Nok yi dañu xam liggéey bu rafet ci fer.",
    },
    artist: "Culture Nok",
    period: "500 av. J.-C.",
    origin: "Nigeria",
    model3dUrl: "/nok2.glb",
    category: "Terre cuite",
    imageUrl: "/nok.jpg",
    qrCode: "MCN-002",
    audioUrl: "/audio/statue-nok.mp3",
  },
  {
    id: "throne-ashanti",
    title: {
      fr: "Trône Ashanti",
      en: "Ashanti Throne",
      wo: "Troon Ashanti",
    },
    description: {
      fr: "Ce trône royal Ashanti du Ghana symbolise le pouvoir et la continuité dynastique. Recouvert de feuilles d'or, il représente l'âme de la nation Ashanti. Chaque élément décoratif raconte une histoire de bravoure et de sagesse.",
      en: "This royal Ashanti throne from Ghana symbolizes power and dynastic continuity. Covered in gold leaf, it represents the soul of the Ashanti nation. Each decorative element tells a story of bravery and wisdom.",
      wo: "Troon bii jëkk na ci Ghana, dafa melni doole ak cosaan bu guddi. Dañu ko tefes ci wàr, te dafa wone ruu réew Ashanti. Bëpp xeetu rafet dafa xalaat ab tarix bu gëna.",
    },
    artist: "Artisans Ashanti",
    period: "18ème siècle",
    model3dUrl: "/trone2.glb",
    origin: "Ghana",
    category: "Mobilier royal",
    imageUrl: "/trone.jpg",
    qrCode: "MCN-003",
    audioUrl: "/audio/throne-ashanti.mp3",
  },
  {
    id: "textile-kente",
    title: {
      fr: "Textile Kente",
      en: "Kente Cloth",
      wo: "Dëkk Kente",
    },
    description: {
      fr: "Le Kente est un tissu traditionnel ghanéen tissé à la main avec des motifs géométriques colorés. Chaque couleur et motif a une signification symbolique. Porté lors de cérémonies importantes, il représente la richesse culturelle et l'identité africaine.",
      en: "Kente is a traditional Ghanaian fabric hand-woven with colorful geometric patterns. Each color and pattern has symbolic meaning. Worn during important ceremonies, it represents cultural wealth and African identity.",
      wo: "Kente dafa am ci Ghana, dañu ko sos ci loxo ak motiif yu melni xeetu yu bari. Bëpp melo ak motiif am na sa teere. Dañu ko samp ci sérémoniy yu bari, te dafa wone boyotu cosaan.",
    },
    artist: "Tisserands Akan",
    period: "Contemporain",
    origin: "Ghana",
    category: "Textile",
    imageUrl: "/textile.jpg",
    qrCode: "MCN-004",
    audioUrl: "/audio/textile-kente.mp3",
  },
  {
    id: "mask-fang",
    title: {
      fr: "Masque Fang",
      en: "Fang Mask",
      wo: "Maask Fang",
    },
    description: {
      fr: "Ce masque blanc Fang du Gabon est utilisé dans les rituels d'initiation. Sa surface lisse et ses traits stylisés incarnent la beauté idéale et la pureté spirituelle. Les Fang sont célèbres pour leur art du masque et leurs reliquaires.",
      en: "This white Fang mask from Gabon is used in initiation rituals. Its smooth surface and stylized features embody ideal beauty and spiritual purity. The Fang are famous for their mask art and reliquaries.",
      wo: "Maask Fang bii jëkk na ci Gabon, dañu ko jëfandikoo ci sérémoniy initiation. Dafa rafet lool te dafa wone rafet bu mat ak pureté spirituelle.",
    },
    artist: "Artisan Fang",
    period: "20ème siècle",
    model3dUrl: "/fang2.glb",
    origin: "Gabon",
    category: "Sculpture",
    imageUrl: "/fang.jpg",
    qrCode: "MCN-005",
    audioUrl: "/audio/mask-fang.mp3",
  },
    {
    id: "femme-fs",
    title: {
      fr: "Femme fs",
      en: "Fang Mask",
      wo: "Maask Fang",
    },
    description: {
      fr: "Ce masque blanc Fang du Gabon est utilisé dans les rituels d'initiation. Sa surface lisse et ses traits stylisés incarnent la beauté idéale et la pureté spirituelle. Les Fang sont célèbres pour leur art du masque et leurs reliquaires.",
      en: "This white Fang mask from Gabon is used in initiation rituals. Its smooth surface and stylized features embody ideal beauty and spiritual purity. The Fang are famous for their mask art and reliquaries.",
      wo: "Maask Fang bii jëkk na ci Gabon, dañu ko jëfandikoo ci sérémoniy initiation. Dafa rafet lool te dafa wone rafet bu mat ak pureté spirituelle.",
    },
    artist: "Artisan Fang",
    period: "20ème siècle",
    model3dUrl: "/femme_fs1.glb",
    origin: "Gabon",
    category: "Sculpture",
    imageUrl: "/femme_fs.webp",
    qrCode: "MCN-005",
    audioUrl: "/audio/mask-fang.mp3",
  },
   {
    id: "femme-ch",
    title: {
      fr: "Femme h",
      en: "Fang Mask",
      wo: "Maask Fang",
    },
    description: {
      fr: "Ce masque blanc Fang du Gabon est utilisé dans les rituels d'initiation. Sa surface lisse et ses traits stylisés incarnent la beauté idéale et la pureté spirituelle. Les Fang sont célèbres pour leur art du masque et leurs reliquaires.",
      en: "This white Fang mask from Gabon is used in initiation rituals. Its smooth surface and stylized features embody ideal beauty and spiritual purity. The Fang are famous for their mask art and reliquaries.",
      wo: "Maask Fang bii jëkk na ci Gabon, dañu ko jëfandikoo ci sérémoniy initiation. Dafa rafet lool te dafa wone rafet bu mat ak pureté spirituelle.",
    },
    artist: "Artisan Fang",
    period: "20ème siècle",
    model3dUrl: "/femme_ch1.glb",
    origin: "Gabon",
    category: "Sculpture",
    imageUrl: "/femme_ch.webp",
    qrCode: "MCN-005",
    audioUrl: "/audio/mask-fang.mp3",
  },
    {
    id: "buf-ch",
    title: {
      fr: "Femme h",
      en: "Fang Mask",
      wo: "Maask Fang",
    },
    description: {
      fr: "Ce masque blanc Fang du Gabon est utilisé dans les rituels d'initiation. Sa surface lisse et ses traits stylisés incarnent la beauté idéale et la pureté spirituelle. Les Fang sont célèbres pour leur art du masque et leurs reliquaires.",
      en: "This white Fang mask from Gabon is used in initiation rituals. Its smooth surface and stylized features embody ideal beauty and spiritual purity. The Fang are famous for their mask art and reliquaries.",
      wo: "Maask Fang bii jëkk na ci Gabon, dañu ko jëfandikoo ci sérémoniy initiation. Dafa rafet lool te dafa wone rafet bu mat ak pureté spirituelle.",
    },
    artist: "Artisan Fang",
    period: "20ème siècle",
    model3dUrl: "/buf1.glb",
    origin: "Gabon",
    category: "Sculpture",
    imageUrl: "/buf.webp",
    qrCode: "MCN-005",
    audioUrl: "/audio/mask-fang.mp3",
  },
  {
    id: "bronze-benin",
    title: {
      fr: "Bronze du Bénin",
      en: "Benin Bronze",
      wo: "Bronz Bénin",
    },
    description: {
      fr: "Cette plaque en bronze du Royaume du Bénin (actuel Nigeria) date du 16ème siècle. Elle ornait les murs du palais royal et représente des scènes de cour. Les bronzes du Bénin témoignent d'une maîtrise technique exceptionnelle de la fonte à la cire perdue.",
      en: "This bronze plaque from the Kingdom of Benin (present-day Nigeria) dates from the 16th century. It adorned the walls of the royal palace and depicts court scenes. The Benin bronzes demonstrate exceptional technical mastery of lost-wax casting.",
      wo: "Plak bronz bii jëkk na ci Réew Bénin (Nigeria leegi) ci 16ème siècle. Dañu ko defar ci kër bu buur te dafa wone xeetu kër bu buur. Bronz Bénin yi dafa gëna ci xam-xam bu rafet.",
    },
    artist: "Artisans Edo",
    period: "16ème siècle",
    origin: "Nigeria",
    category: "Bronze",
    imageUrl: "/bronze.jpg",
    qrCode: "MCN-006",
    audioUrl: "/audio/bronze-benin.mp3",
  },
]
